locale                   : "en-US"
title                    : "FXYXHF/ Homepage"
title_separator          : "-"
name                     : "FXYXHF"
description              : "Master Candidate"
url                      : "https://fxyxhf.github.io"
baseurl                  : "/lbx2zyx"
repository               : ""

author:
  avatar           : "1.png"
  name             : "FXYXHF 凤先又寻欢飞、"
  pronouns         : "才子词人，自是白衣卿相"
  bio              : "Harbin Institute of Technology"
  location         : "Harbin, China"
  employer         : 
  uri              :
  email            : "lubx_2021@163.com"

  arxiv            :
  googlescholar    : "https://scholar.google.com/citations?user=quW8VIwAAAAJ&hl=zh-CN&oi=ao"
  impactstory      :
  orcid            : "https://orcid.org/0009-0009-5260-6171"
  semantic         :
  pubmed           :
  researchgate     :

  bitbucket        :
  codepen          :
  dribbble         :
  github           : "https://github.com/fxyxhf"
  kaggle           :
  stackoverflow    :

  WeChat           : "images/weixin.png" 
  linkedin         :
  bilibili         : "https://space.bilibili.com/1733155550?spm_id_from=333.788.0.0"
  twitter          :
  youtube          :
  zhihu            : "https://www.zhihu.com/people/feng-xian-you-xun-huan-fei" 
  XiaoHongShu      :

teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

comments:
  provider               :
  disqus:
    shortname            :
  discourse:
    server               :
  facebook:
    appid                :
    num_posts            :
    colorscheme          :

staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"

atom_feed:
  hide                   : false
  path                   :

google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :
social:
  type                   :
  name                   :
  links                  : []

analytics:
  provider               : false
  google:
    tracking_id          :

include:
  - .htaccess
  - _pages
  - files

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Asia/Shanghai

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development

plugins:
  - jekyll-paginate

paginate: 10     
paginate_path: "/posts/page:num/"
